config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  devise_for :users, skip: [:password], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  
  namespace :admin do
    root to: "homes#top"
    resources :posts, only: [:show, :destroy]
    resources :comments, only: [:destroy]
    resources :users, param: :name, only: [:index, :show, :edit, :update]
    get "search" => "searches#search"
    get "tagsearch" => "tagsearches#search"
  end
  
  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"
    resource :map, only: [:show]
    resources :users, param: :name, only: [:show, :edit, :update] do
      member do
        get "laughed_posts"
        get "follows_show"
      end
      collection do
        patch "withdraw"
      end
    end
    resources :posts do
      collection do
        get "draft"
      end
      resources :comments, only: [:create, :destroy]
      resource :laughed_buttons, only: [:create, :destroy]
    end
    resources :follows, only: [:index, :create, :destroy]
    resources :notifications, only: :index
    get 'search' => "searches#search"
    get "tagsearch" => "tagsearches#search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    before_action :authenticate_admin!
    
    def top
        respond_to do |format|
            format.html do
                @posts = Post.page(params[:page])
            end
            format.json do
                @posts = Post.all
            end
        end
        
        @published_posts = Post.published.order(created_at: :desc).page(params[:page])
    end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="container-fluid">
    <h2>投稿一覧</h2>
    <div class="row">
        <% @published_posts.each do |post| %>
            <div class="col-4 border p-1">
                <div class="row">
                    <div class="col-5">
                        <%= link_to(admin_post_path(post)) do %>
                            <%= image_tag post.get_image(200,200) %>
                        <% end %>
                    </div>
                    
                    <div class="col-7 pr-5">
                        <div class="row">
                            <div class="col-1 p-0"><%= image_tag post.user.get_profile_image(40,40), class: "rounded-circle" %></div>
                            <p class="col-10 h6 font-weight-bold align-middle ml-2"><%= post.posted_title.truncate(19) %></p>
                        </div>
                        <div class="text-break col mt-2"><%= post.post_content.truncate(103) %></div>
                        <div class="mt-2"><%= render "public/posts/post", post: post %></div>
                        <p class="row">
                            <span><i class="fa-solid fa-location-dot"></i> <%= post.address %></span>
                        </p>
                        <div class="row mt-4 d-flex justify-content-end">
                            <div class="mr-2" id="laughed_buttons_<%= post.id %>">
                                <%= render "public/laughed_buttons/laughed", post: post %>
                            </div>
                            <div id="comment_counter">
                                <%= render "public/comments/counter", post: post %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>
<div class="d-flex justify-content-center">
    <%= paginate @published_posts %>
</div>