config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  devise_for :users, skip: [:password], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  
  namespace :admin do
    root to: "homes#top"
    resources :posts, only: [:show, :destroy]
    resources :comments, only: [:destroy]
    resources :users, param: :name, only: [:index, :show, :edit, :update]
    get "search" => "searches#search"
    get "tagsearch" => "tagsearches#search"
  end
  
  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"
    resource :map, only: [:show]
    resources :users, param: :name, only: [:show, :edit, :update] do
      member do
        get "laughed_posts"
        get "follows_show"
      end
      collection do
        patch "withdraw"
      end
    end
    resources :posts do
      collection do
        get "draft"
      end
      resources :comments, only: [:create, :destroy]
      resource :laughed_buttons, only: [:create, :destroy]
    end
    resources :follows, only: [:index, :create, :destroy]
    resources :notifications, only: :index
    get 'search' => "searches#search"
    get "tagsearch" => "tagsearches#search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :laughed_buttons, dependent: :destroy
  has_many :followers, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'recipient_user_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'sender_user_id', dependent: :destroy
  has_one_attached :profile_image
  
  validates :name, uniqueness: true, presence: true
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      logger.debug "profile image is not attached"
      file_path = Rails.root.join("app/assets/images/ashiato.jpg")
      profile_image.attach(io: File.open(file_path), filename: "ashiato.jpg", content_type: "image/jpg")
    end
    profile_image.variant(resize_to_fill: [width, height]).processed
  end
  
  def status_label
    status_class = is_active? ? "text-success" : "text-secondary"
    "<span class='#{status_class}'>#{is_active? ? '有効' : '退会'}</span>".html_safe
  end

  GUEST_USER_EMAIL = "guest@user.com"
  
  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
      user.id = 0
    end
  end
  
  def guest_user?
    email == GUEST_USER_EMAIL
  end
  
  def self.search_for(content, method)
    if method == "perfect"
      User.where(name: content)
    elsif method == "forward"
      User.where("name LIKE ?", content + "%")
    elsif method == "backward"
      User.where("name LIKE ?", "%" + content)
    else
      User.where("name LIKE ?", "%" + content + "%")
    end
  end
  
  def create_notification_follow!(current_user)
    temp = Notification.where(["recipient_user_id = ? and sender_user_id = ? and notification_type = ?", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        sender_user_id: id,
        notification_type: 'follow'
      )
      notification.save if notification.valid?
    end
  end
  
  def to_param
    name
  end
  
  validates :name,
    format: { with: /\A[a-z0-9_-]+\Z/ },
    length: { minimum: 3, maximum: 25}
    
  def following?(current_user, follow_id)
    Follower.find_by(user_id: follow_id, follow_id: current_user.id)
  end
  
  def followed(user)
    Follower.where(follow_id: user.id)
  end
  
  def follower(current_user)
    Follower.where(user_id: current_user.id)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :authenticate_admin!
    before_action :ensure_admin, only: [:edit]
    
    def index
        @users = User.page(params[:page]).per(10)
    end
    
    def show
        @user = User.find_by(name: params[:name])
        respond_to do |format|
            format.html do
                @posts = Post.page(params[:page])
            end
            format.json do
                @posts = Post.all
            end
        end
        @published_posts = @user.posts.published.order(created_at: :desc).page(params[:page])
        @draft_posts = @user.posts.draft.order(created_at: :desc).page(params[:page])
        @unpublished_posts = @user.posts.unpublished.order(created_at: :desc).page(params[:page])
    end
    
    def edit
        @user = User.find_by(name: params[:name])
    end
    
    def update
        user = User.find_by(name: params[:name])
        user.update(user_params)
        redirect_to admin_user_path(user)
    end
    
    private
    
    def user_params
        params.require(:user).permit(:name, :email, :is_active)
    end
    
    def ensure_admin
        user = User.find_by(name: params[:name])
        if user.guest_user?
            redirect_to admin_user_path(user), notice: "ゲストユーザーのプロフィール編集はできません。"
        end
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_index.html.erb
<table class="table table-bordered">
    <tr>
        <th class="col-1 text-center">会員ID</th>
        <th>名前</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
    </tr>
    <% users.each do |user| %>
        <tr>
            <td class="text-center"><%= user.id %></td>
            <td>
                <%= link_to user.name, admin_user_path(user), class: "text-dark font-weight-bold" %>
            </td>
            <td><%= user.email %></td>
            <td><%= user.status_label %></td>
        </tr>
    <% end %>
</table>

app/views/admin/users/edit.html.erb
<div class="container">
    <h2>会員情報編集</h2>
    <div class="row mt-5">
        <div class="col d-flex justify-content-center">
            <%= form_with model: [:admin, @user] do |f| %>
            <table class="table table-lg table-borderless">
                <tr class="row">
                    <th class="col-5">会員ID</th>
                    <td class="col-5"><%= @user.id %></td>
                </tr>
                
                <tr class="row">
                    <th class="col-5">名前</th>
                    <td class="col-5"><%= f.text_field :name %></td>
                </tr>
                
                <tr class="row">
                    <th class="col-5">メールアドレス</th>
                    <td class="col-5"><%= f.email_field :email %></td>
                </tr>
                
                <tr class="row">
                    <th class="col-5">会員ステータス</th>
                    <td class="col-3">
                        <%= f.radio_button :is_active, :true %>
                        <%= f.label :is_active, "有効", {value: true} %>
                    </td>
                    <td class="col-3">
                        <%= f.radio_button :is_active, :false %>
                        <%= f.label :is_active, "退会", {value: false} %>
                    </td>
                </tr>
            </table>
            <div class="text-center"><%= f.submit "変更を保存" %></div>
            <% end %>
        </div>
    </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
    <h2>会員一覧</h2>
    <div class="row">
        <%= render "index", users: @users %>
    </div>
    <div class="d-flex justify-content-center"><%= paginate @users %></div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
    <h2>会員詳細</h2>
    <div class="row">
        <div class="col-4">
            <table>
                <tr>
                    <th class="col-3">会員ID</th>
                    <td class="col-3"><%= @user.id %></td>
                </tr>
                
                <tr>
                    <th class="col-3">氏名</th>
                    <td class="col-3"><%= @user.name %></td>
                </tr>
                
                <tr>
                    <th class="col-3">メールアドレス</th>
                    <td class="col-3"><%= @user.email %></td>
                </tr>
                
                <tr>
                    <th class="col-3">会員ステータス</th>
                    <td class="col-3"><%= @user.status_label %></td>
                </tr>
            </table>
            <div class="ml-5 mt-2"><%= link_to "編集する", edit_admin_user_path(@user), class: "btn-dark rounded p-1 ml-5" %></div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <h2>投稿一覧</h2>
    <div class="tabs d-flex justify-content-left align-items-center">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#published">公開中</a>
            </li>
            <% if @user == current_user %>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#draft">下書き</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#unpublished">非公開</a>
                </li>
            <% end %>
        </ul>
    </div>
    
    <div class="tab-content">
        <div id="published" class="tab-pane fade show active">
            <div class="row mb-2">
                <% @published_posts.each do |post| %>
                    <%= render "public/posts/index", post: post %>
                <% end %>
            </div>
            <div class="d-flex justify-content-center">
                <%= paginate @published_posts %>
            </div>
        </div>
        
        <div id="draft" class="tab-pane fade">
            <div class="row mb-2">
                <% @draft_posts.each do |post| %>
                    <%= render "public/posts/index", post: post %>
                <% end %>
            </div>
            <div class="d-flex justify-content-center">
                <%= paginate @draft_posts %>
            </div>
        </div>
        
        <div id="unpublished" class="tab-pane fade">
            <div class="row mb-2">
                <% @unpublished_posts.each do |post| %>
                    <%= render "public/posts/index", post: post %>
                <% end %>
            </div>
            <div class="d-flex justify-content-center">
                <%= paginate @unpublished_posts %>
            </div>
        </div>
    </div>
</div>