config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  devise_for :users, skip: [:password], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  
  namespace :admin do
    root to: "homes#top"
    resources :posts, only: [:show, :destroy]
    resources :comments, only: [:destroy]
    resources :users, param: :name, only: [:index, :show, :edit, :update]
    get "search" => "searches#search"
    get "tagsearch" => "tagsearches#search"
  end
  
  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"
    resource :map, only: [:show]
    resources :users, param: :name, only: [:show, :edit, :update] do
      member do
        get "laughed_posts"
        get "follows_show"
      end
      collection do
        patch "withdraw"
      end
    end
    resources :posts do
      collection do
        get "draft"
      end
      resources :comments, only: [:create, :destroy]
      resource :laughed_buttons, only: [:create, :destroy]
    end
    resources :follows, only: [:index, :create, :destroy]
    resources :notifications, only: :index
    get 'search' => "searches#search"
    get "tagsearch" => "tagsearches#search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Animo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/a7b69aa32a.js" crossorigin="anonymous"></script>
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=RocknRoll+One&family=Yusei+Magic&display=swap" rel="stylesheet">
    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body class="d-flex flex-column vh-100 custom_font">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light p-0">
        <div class="container">
          <a class="navbar-brand" href="/"><%= image_tag('logo.png')%></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "投稿一覧", admin_root_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "会員一覧", admin_users_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
              </li>
              
              <% elsif user_signed_in? %>
              <li class="nav-item">
                  <%= link_to notifications_path do %>
                    <% if unchecked_notifications.any? %>
                        <span class="fa-stack" style="position: relative;">
                            <i class="fa-regular fa-envelope fa-stack-2x" style="color: #2b5fda;"></i>
                            <i class="fa-solid fa-circle n-circle fa-stack-1x" style="color: #fa9200; position: absolute; left: 13px; top: 8px;"></i>
                        </span>
                    <% else %>
                        <i class="fa-regular fa-envelope fa-2x nav-link" style="color: #2b5fda;"></i>
                    <% end %>
                  <% end %>
              </li>
              <li class="nav-item">
                <%= link_to "マイページ", user_path(current_user), class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "会員一覧", follows_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "投稿一覧", posts_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "新規投稿", new_post_path, class: 'nav-link text-dark', data: {"turbolinks" => false} %>
              </li>
              <li class="nav-item">
                <%= link_to "マップ", map_path, class: 'nav-link text-dark', data: {"turbolinks" => false} %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
              </li>
              
              <% else %>
              <li class="nav-item">
                <%= link_to "About", about_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <nav class="navbar navbar-expand-lg navbar-light">
      <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
        <li class="nav-item mr-2">
          <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
            <%= f.text_field :content %>
            <%= f.select :model, options_for_select({"User" => "user", "Post" => "post"}) %>
            <%= f.select :method, options_for_select({"完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial"}) %>
            <%= f.submit "検索" %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= form_with url: tagsearch_path, method: :get, loacl: true do |f| %>
            <%= f.text_field :content %>
            <%= f.submit "タグ検索" %>
          <% end %>
        </li>
        <% elsif user_signed_in? %>
        <li class="nav-item mr-4">
          <%= form_with url: search_path, local: true, method: :get do |f| %>
            <%= f.text_field :content %>
            <%= f.select :model, options_for_select({"User" => "user", "Post" => "post"}) %>
            <%= f.select :method, options_for_select({"完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial"}) %>
            <%= f.submit "検索" %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= form_with url: tagsearch_path, method: :get, loacl: true do |f| %>
            <%= f.text_field :content %>
            <%= f.submit "タグ検索" %>
          <% end %>
        </li>
        <% else %>
        <% end %>
      </ul>
    </nav>
    </header>
    <main class="mt-5 mb-auto mx-5">
      <%= flash[:notice] %>
      <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-4 text-center">
            <p>© 2024 あにも</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>